# Generated by Django 5.2.6 on 2026-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#374151', max_length=7)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['y', 'x'],
                'unique_together': {('x', 'y')},
            },
        ),
    ]
